# Generated by Django 4.0.1 on 2023-01-31 18:27

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0044_merge_20230131_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='additional_number',
        ),
        migrations.AlterField(
            model_name='additionalusernumber',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментраий'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
